# -*- coding: utf-8 -*-
"""hospital_ledger_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvPNMiHBjiFczreDTQm0Hxg40vIY8kwp
"""

import streamlit as st
from datetime import datetime

# Initialize the session state for storing patient records
if 'hospital_ledger_advanced' not in st.session_state:
    st.session_state.hospital_ledger_advanced = {}

# App title
st.title("🏥 Hospital Ledger - Advanced Patient Visit Tracker")

# Form to add a new patient visit
with st.form("add_visit_form"):
    st.subheader("➕ Add New Patient Visit")

    patient_name = st.text_input("Patient Name")
    treatment = st.text_input("Treatment Received")
    cost = st.number_input("Cost of Treatment ($)", min_value=0.0, step=0.01, format="%.2f")
    date_of_visit = st.date_input("Date of Visit", value=datetime.today())

    submitted = st.form_submit_button("Add Visit")

    if submitted:
        if patient_name and treatment:
            visit = {
                "treatment": treatment,
                "cost": cost,
                "date_of_visit": date_of_visit.strftime("%Y-%m-%d")
            }

            if patient_name not in st.session_state.hospital_ledger_advanced:
                st.session_state.hospital_ledger_advanced[patient_name] = []

            st.session_state.hospital_ledger_advanced[patient_name].append(visit)

            st.success(f"Visit added for {patient_name} on {visit['date_of_visit']} for treatment '{treatment}' costing ${cost:.2f}")
        else:
            st.warning("Please enter both the patient name and treatment.")

# Display the patient records
st.subheader("📒 Patient Visit Records")

if st.session_state.hospital_ledger_advanced:
    for patient, visits in st.session_state.hospital_ledger_advanced.items():
        st.markdown(f"### 👤 Patient: *{patient}*")
        for visit in visits:
            st.markdown(f"- 🩺 Treatment: *{visit['treatment']}* | 💰 Cost: *${visit['cost']}* | 📅 Date: *{visit['date_of_visit']}*")
else:
    st.info("No visits recorded yet. Please add a patient visit above.")